#!/bin/bash

# David Lettier (C) 2014.

echo ""
echo "   ___       _       ___            "
echo "  |_  |     | |     |_  |           "
echo "    | | ___ | |__     | | __ _ _ __ "
echo "    | |/ _ \| '_ \    | |/ \` | '__|"
echo "/\__/ / (_) | |_) /\__/ / (_| | |   " 
echo "\____/ \___/|_.__/\____/ \__,_|_|   "
echo ""

echo ""
echo "---------------------------------------------------"
echo "Starting node..."
echo "---------------------------------------------------"
echo ""

node ./node_modules/nodemon/bin/nodemon.js ./source/server.js & 

sleep 2 

echo ""
echo "---------------------------------------------------"
echo "Opening your browser to JobJar..."
echo "---------------------------------------------------"
echo ""

xdg-open http://localhost:8888 &